openapi: 3.2.0
info:
  title: Visier Administration Sidecar Solutions API
  description: Visier APIs for managing your tenant or tenants in Visier. You can programmatically manage user accounts in Visier, the profiles and permissions assigned to users, and to make changes in projects and publish projects to production. Administrating tenant users can use administration APIs to manage their analytic tenants and consolidated analytics tenants.<br>**Note:** If you submit API requests for changes that cause a project to publish to production (such as assigning permissions to users or updating permissions), each request is individually published to production, resulting in hundreds or thousands of production versions. We recommend that you use the `ProjectID` request header to make changes in a project, if `ProjectID` is available for the API endpoint.
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0
  version: 22222222.99201.3040
security:
- ApiKeyAuth: []
  BearerAuth: []
- ApiKeyAuth: []
  CookieAuth: []
- ApiKeyAuth: []
  OAuth2Auth: []
tags:
- name: SidecarSolutions
  x-displayName: Sidecar Solutions
  description: 'Manage your sidecar solution''s configuration. A sidecar solution is a unique solution built using the Visier platform, such as Smart Compensation. Use this API to retrieve the current settings, update the settings to new values, or delete existing settings.

    <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.

    If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>'
paths:
  /v1alpha/admin/sidecar-app-configs/{applicationId}:
    get:
      tags:
      - SidecarSolutions
      summary: Retrieve a sidecar solution's settings
      description: "Retrieve the settings for a specific sidecar solution. You must know the solution ID of your sidecar solution. To get the ID, contact Visier Technical Support.\n\n <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.\n If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>"
      operationId: SidecarSolutions_GetSidecarSolutionSettings
      parameters:
      - name: applicationId
        in: path
        description: The unique identifier of the solution to configure.
        required: true
        schema:
          type: string
      - name: TargetTenantID
        in: header
        description: Optionally, specify the tenant that you want to execute the API call on. This defines the tenant that you're logged into. If omitted, the request uses the administrating tenant as the login tenant.
        schema:
          type: string
      responses:
        default:
          description: Default error response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Status'
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servicing.SidecarSolutionSettingsDTO'
    put:
      tags:
      - SidecarSolutions
      summary: Update a sidecar solution's settings
      description: "Update a sidecar solution's settings. The response returns the settings after updating. When updating setting, we recommend that you first retrieve the existing settings using `GET`. You can use the `GET` response in your `PUT` request definition.\n\n In `PUT` requests, the definition in your API call replaces the prior definition. You must provide the entire definition in the `PUT` call. If you omit values from the update request, those values are removed.\n\n <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.\n If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>"
      operationId: SidecarSolutions_SetSidecarAppConfigs
      parameters:
      - name: applicationId
        in: path
        description: The unique identifier of the solution to configure.
        required: true
        schema:
          type: string
      - name: TargetTenantID
        in: header
        description: Optionally, specify the tenant that you want to execute the API call on. This defines the tenant that you're logged into. If omitted, the request uses the administrating tenant as the login tenant.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/servicing.SidecarSolutionSettingsDTO'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/servicing.SidecarSolutionSettingsDTO'
    delete:
      tags:
      - SidecarSolutions
      summary: Delete a sidecar solution's settings
      description: "Delete the settings for a sidecar solution. This deletes all the settings for the solution.\n\n <br>**Note:** <em>This API is in **alpha**. While in alpha, APIs may change in a breaking way without notice; functionality may be removed, and no deprecation notices will be issued.\n If you are interested in using this API, please contact your Customer Success Manager (CSM).</em>"
      operationId: SidecarSolutions_DeleteSidecarAppConfigs
      parameters:
      - name: applicationId
        in: path
        description: The unique identifier of the solution to configure.
        required: true
        schema:
          type: string
      - name: TargetTenantID
        in: header
        description: Optionally, specify the tenant that you want to execute the API call on. This defines the tenant that you're logged into. If omitted, the request uses the administrating tenant as the login tenant.
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/admin.SidecarSolutionRequestDTO'
        required: true
      responses:
        '200':
          description: OK
          content: {}
components:
  schemas:
    servicing.SettingsDTO:
      type: object
      properties:
        key:
          type: string
          description: The key of the configurable setting.
        singleConfigItem:
          allOf:
          - $ref: '#/components/schemas/servicing.SingleValueSettingDTO'
          description: A value containing a single string.
        multiValueConfigItem:
          allOf:
          - $ref: '#/components/schemas/servicing.MultiValueSettingDTO'
          description: A value containing multiple strings.
      description: The settings to configure a sidecar solution.
    servicing.MultiValueSettingDTO:
      type: object
      properties:
        values:
          type: array
          items:
            type: string
          description: A value containing multiple strings.
      description: A value containing multiple strings.
    admin.SidecarSolutionRequestDTO:
      type: object
      properties:
        applicationId:
          type: string
          description: The unique identifier of the solution to configure.
    servicing.SingleValueSettingDTO:
      type: object
      properties:
        value:
          type: string
          description: A value containing a single string.
      description: A value containing a single string.
    Status:
      type: object
      properties:
        localizedMessage:
          type: string
          description: Localized error message describing the root cause of the error.
        code:
          type: string
          description: Error classification.
        message:
          type: string
          description: Not used.
        rci:
          type: string
          description: Optional root cause identifier.
        userError:
          type: boolean
          description: Indicates whether the error is a user error.
      description: The response structure for errors.
    servicing.SidecarSolutionSettingsDTO:
      type: object
      properties:
        configs:
          type: array
          items:
            $ref: '#/components/schemas/servicing.SettingsDTO'
          description: The available configuration settings.
        applicationId:
          type: string
          description: The unique identifier of the solution to configure.
      description: The options to configure a sidecar solution.
  securitySchemes:
    CookieAuth:
      type: apiKey
      name: VisierASIDToken
      in: cookie
    ApiKeyAuth:
      type: apiKey
      name: apikey
      in: header
    BearerAuth:
      type: http
      scheme: bearer
    OAuth2Auth:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /v1/auth/oauth2/authorize
          tokenUrl: /v1/auth/oauth2/token
          scopes:
            read: Grants read access
            write: Grants write access
        password:
          tokenUrl: /v1/auth/oauth2/token
          scopes:
            read: Grants read access
            write: Grants write access
x-tagGroups:
- name: administration
  tags:
  - Projects
  - ProductionVersions
  - UsersV3
  - UsersV2
  - UserGroupsV2
  - UsersV1
  - Profiles
  - Permissions
  - TenantsV2
  - TenantsV1
  - ConsolidatedAnalytics
  - Sources
  - SystemStatus
  - EmailDomains
  - EncryptionKeys
  - NetworkSubnets
  - SidecarSolutions
  - ReleaseVersionConfiguration
  - VeeConfiguration
